# Generated by Django 4.1.1 on 2022-09-08 20:45

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("new", "New"),
                            ("moderated", "Moderated"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                        ],
                        default="new",
                        max_length=50,
                        protected=True,
                    ),
                ),
            ],
        ),
    ]
