# Generated by Django 4.1.3 on 2022-12-01 09:04

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="step",
            field=django_fsm.FSMField(
                choices=[("step1", "Step one"), ("step2", "Step two"), ("step3", "Step three")],
                default="step1",
                max_length=50,
            ),
        ),
    ]
