# Generated by Django 4.1.1 on 2022-09-08 20:49

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("moderated", "Moderated"),
                    ("published", "Published"),
                    ("hidden", "Hidden"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
